"""empty message

Revision ID: dc9cc80bbc13
Revises: a1e0ee346574
Create Date: 2024-09-28 20:22:11.937062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9cc80bbc13'
down_revision = 'a1e0ee346574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('origin',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('origin',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
