"""empty message

Revision ID: c19f7796ccee
Revises: 77a5a0ab4ee6
Create Date: 2024-10-10 20:42:56.796993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19f7796ccee'
down_revision = '77a5a0ab4ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brief_description', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('categorie_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('producer_id', sa.Integer(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'product_categories', ['categorie_id'], ['id'])
        batch_op.create_foreign_key(None, 'producer', ['producer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('producer_id')
        batch_op.drop_column('categorie_id')
        batch_op.drop_column('brief_description')

    # ### end Alembic commands ###
