"""empty message

Revision ID: e0809e458fb0
Revises: 757f1e12b289
Create Date: 2024-10-11 13:35:40.688842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0809e458fb0'
down_revision = '757f1e12b289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=40), nullable=False))
        batch_op.drop_constraint('product_categories_categorie_key', type_='unique')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('categorie')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categorie', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('product_categories_categorie_key', ['categorie'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###
