"""empty message

Revision ID: 4cf746ddd2bc
Revises: 9c3ba41159b4
Create Date: 2024-10-02 15:16:23.074207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf746ddd2bc'
down_revision = '9c3ba41159b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'province', ['province_id'], ['id'])
        batch_op.drop_column('province')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('province_id')

    op.drop_table('province')
    # ### end Alembic commands ###
