"""empty message

Revision ID: d2b0cce2765c
Revises: 3e5243bdb2c5
Create Date: 2024-10-04 17:11:44.935105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b0cce2765c'
down_revision = '3e5243bdb2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart__products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Numeric(precision=100), nullable=False),
    sa.Column('product_id', sa.Numeric(precision=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart__items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_cart_id', sa.Numeric(precision=100), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Numeric(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('cart_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart__items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.NUMERIC(precision=100, scale=0), autoincrement=False, nullable=False))
        batch_op.drop_column('total_price')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('price')
        batch_op.drop_column('quantity')
        batch_op.drop_column('customer_cart_id')

    op.drop_table('cart__products')
    # ### end Alembic commands ###
