"""empty message

Revision ID: 08954d43ed25
Revises: d88b38c2b720
Create Date: 2024-10-03 13:01:19.330529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08954d43ed25'
down_revision = 'd88b38c2b720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('zipcode',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=14),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('zipcode',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('province',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
