"""empty message

Revision ID: 21ee1ce5d8fa
Revises: 5d98679cc3e4
Create Date: 2024-09-28 10:08:31.776207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ee1ce5d8fa'
down_revision = '5d98679cc3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categorie', sa.String(length=40), nullable=False))
        batch_op.drop_constraint('product_categories_catetorie_key', type_='unique')
        batch_op.create_unique_constraint(None, ['categorie'])
        batch_op.drop_column('catetorie')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catetorie', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('product_categories_catetorie_key', ['catetorie'])
        batch_op.drop_column('categorie')

    # ### end Alembic commands ###
