"""empty message

Revision ID: 54d228326ff9
Revises: b7d7fc9f44b8
Create Date: 2024-10-13 19:35:16.171158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d228326ff9'
down_revision = 'b7d7fc9f44b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('received', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('processing', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('shipped', sa.String(length=50), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('shipped')
        batch_op.drop_column('processing')
        batch_op.drop_column('received')
        batch_op.drop_column('new')

    # ### end Alembic commands ###
