"""empty message

Revision ID: 8d1e9292bb99
Revises: 1214f92c1b2e
Create Date: 2024-10-07 17:02:24.667452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1e9292bb99'
down_revision = '1214f92c1b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageUrl', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_column('imageUrl')

    # ### end Alembic commands ###
