"""empty message

Revision ID: b7d7fc9f44b8
Revises: eb70590baafe
Create Date: 2024-10-13 19:20:23.921810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d7fc9f44b8'
down_revision = 'eb70590baafe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    with op.batch_alter_table('customer_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'producer', ['producer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('producer_id')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
