"""empty message

Revision ID: c39d95941ac1
Revises: 72ae9a439b42
Create Date: 2024-10-12 05:45:37.578324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39d95941ac1'
down_revision = '72ae9a439b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('categorie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('producer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('producer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('categorie_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
