"""empty message

Revision ID: cbd1e36d8ef7
Revises: 2725bbfafb7c
Create Date: 2024-09-28 16:11:37.078597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd1e36d8ef7'
down_revision = '2725bbfafb7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('user_last_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producer', schema=None) as batch_op:
        batch_op.drop_column('user_last_name')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
