"""empty message

Revision ID: eb70590baafe
Revises: 94fb4ffe35e2
Create Date: 2024-10-13 18:56:11.164804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb70590baafe'
down_revision = '94fb4ffe35e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'producer', ['producer_id'], ['id'])
        batch_op.create_foreign_key(None, 'customer_cart', ['customer_cart_id'], ['id'])
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('producer_id')

    # ### end Alembic commands ###
