"""empty message

Revision ID: 498c5e836e77
Revises: 953e4c5d120d
Create Date: 2024-10-03 10:17:10.098186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498c5e836e77'
down_revision = '953e4c5d120d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=False))
        batch_op.drop_column('adress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adress', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
