"""empty message

Revision ID: 953e4c5d120d
Revises: 3f89cb13b144
Create Date: 2024-10-02 17:15:17.352789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953e4c5d120d'
down_revision = '3f89cb13b144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('aviation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aviation', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
