"""empty message

Revision ID: 5277dc85de72
Revises: 9f722b91b1d5
Create Date: 2024-10-13 08:29:51.913572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5277dc85de72'
down_revision = '9f722b91b1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=40), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('zipcode',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('zipcode',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.drop_column('city')

    # ### end Alembic commands ###
