"""empty message

Revision ID: 5653652ba0b5
Revises: 5277dc85de72
Create Date: 2024-10-14 13:53:28.685461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5653652ba0b5'
down_revision = '5277dc85de72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=60), nullable=True))
        batch_op.drop_constraint('producer_phone_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producer', schema=None) as batch_op:
        batch_op.create_unique_constraint('producer_phone_key', ['phone'])
        batch_op.drop_column('city')

    # ### end Alembic commands ###
