"""added product status model

Revision ID: e5392386dded
Revises: c7a98b7f8c21
Create Date: 2024-10-13 10:36:04.126525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5392386dded'
down_revision = 'c7a98b7f8c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('AVAILABLE', 'NOT_AVAILABLE', 'LAST_UNITS', 'SOON', name='productstatus'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
