"""empty message

Revision ID: 17a092896601
Revises: f90da6de35c6
Create Date: 2024-09-28 16:51:40.795816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a092896601'
down_revision = 'f90da6de35c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('brand_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('province', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('cif', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='producer_pkey'),
    sa.UniqueConstraint('brand_name', name='producer_brand_name_key'),
    sa.UniqueConstraint('cif', name='producer_cif_key'),
    sa.UniqueConstraint('email', name='producer_email_key'),
    sa.UniqueConstraint('phone', name='producer_phone_key')
    )
    # ### end Alembic commands ###
