"""empty message

Revision ID: b21d6a1c4488
Revises: 21ee1ce5d8fa
Create Date: 2024-09-28 15:33:59.247788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21d6a1c4488'
down_revision = '21ee1ce5d8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('brand_name', sa.String(length=80), nullable=False),
    sa.Column('adress', sa.String(length=150), nullable=False),
    sa.Column('province', sa.String(length=150), nullable=False),
    sa.Column('cif', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_name'),
    sa.UniqueConstraint('cif'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producer')
    # ### end Alembic commands ###
