"""empty message

Revision ID: c8b027c4c3a7
Revises: cbd1e36d8ef7
Create Date: 2024-09-30 19:26:46.486372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b027c4c3a7'
down_revision = 'cbd1e36d8ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producer', schema=None) as batch_op:
        batch_op.alter_column('brand_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('cif',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('zip_code',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producer', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('zip_code',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('cif',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('brand_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
