"""empty message

Revision ID: f90da6de35c6
Revises: b21d6a1c4488
Create Date: 2024-09-28 15:38:44.306531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90da6de35c6'
down_revision = 'b21d6a1c4488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=150), nullable=False))
        batch_op.drop_column('adress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adress', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
