"""empty message

Revision ID: 059141105702
Revises: 55dd2c87b891
Create Date: 2024-10-11 20:19:22.428032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059141105702'
down_revision = '55dd2c87b891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'producer', ['producer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('producer_id')

    # ### end Alembic commands ###
